/*
  This JSON object contains the static data for panels used by all students, as well as the initial student progress data for a student
  who has just started.
*/
basePanels = {
  "basic-info": {
    id: "basic-info",
    title: "Basic Information",
    mode: "debug",
    displayType: "tableType",
    complete: false,
    locked: false,
    minimized: false,
    prereqs: false,
    features: [
      {
        type: "variable",
        expressionExpected: "t.firstName",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.lastName",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.age",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.slogan",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      // {
      //   type: "variable",
      //   expressionExpected: "t.favoriteElement",
      //   expressionEntered: '',
      //   hasReturnValue: true,
      //   status: "empty",
      //   complete: false,
      // },
      // {
      //   type: "variable",
      //   expressionExpected: "t.favoriteColor",
      //   expressionEntered: '',
      //   hasReturnValue: true,
      //   status: "empty",
      //   complete: false,
      // },
    ]
  },
  "current-state": {
    id: "current-state",
    title: "Trainer Status",
    mode: "debug",
    displayType: "barType",
    complete: false,
    locked: false,
    minimized: false,
    prereqs: false,
    // prereqs: ["basic-info"],
    features: [
      {
        type: "variable",
        expressionExpected: "t.energy",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.happiness",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.confidence",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.intelligence",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "variable",
        expressionExpected: "t.strength",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      // {
      //   type: "variable",
      //   expressionExpected: "t.coins",
      // expressionEntered: '',
      //   hasReturnValue: true,
      // status: "empty",
      // complete: false,
      // }
    ]
  },
  "name": {
    id: "name",
    title: "Name",
    mode: "debug",
    displayType: "tableType",
    complete: false,
    locked: false,
    minimized: false,
    // prereqs: ['current-state'],
    prereqs: false,
    features: [
      {
        type: "method",
        expressionExpected: "t.getFullName()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getReverseName()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getDoubleFullName()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getDoubleReverseName()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getImageFileName()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getFirstNameLastInitial()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getFirstNameLastInitial()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      }
    ]
  },
  "age": {
    id: "age",
    title: "Age",
    mode: "debug",
    displayType: "tableType",
    complete: false,
    locked: true,
    minimized: false,
    prereqs: false,
    // prereqs: ["name"],
    features: [
      {
        type: "method",
        expressionExpected: "t.getAgeInMonths()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getAgeInWeeks()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getAgeInDays()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getAgeInHours()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getAgeInMinutes()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.getAgeInSeconds()",
        expressionEntered: '',
        hasReturnValue: true,
        status: "empty",
        complete: false,
      },
    ]
  },
  "communicate": {
    id: "communicate",
    title: "Communicate",
    mode: "debug",
    displayType: "void",
    complete: false,
    locked: false,
    minimized: false,
    prereqs: false,
    // prereqs: ["age"],
    features: [
      {
        type: "method",
        expressionExpected: "t.writeHi()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.writeSlogan()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.write()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.sayHi()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.saySlogan()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.say(something)",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
    ]
  },
  "activities": {
    id: "activities",
    title: "Activities",
    mode: "debug",
    displayType: "void",
    complete: false,
    locked: true,
    minimized: false,
    prereqs: ["communicate"],
    features: [
      {
        type: "method",
        expressionExpected: "t.work()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.rest()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.exercise(...)",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.watchTelevision()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.readBook()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.takeCompliment()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
      {
        type: "method",
        expressionExpected: "t.takeInsult()",
        expressionEntered: '',
        hasReturnValue: false,
        status: "empty",
        complete: false,
      },
    ]
  }
}

// features = {}
// var panelsArray = Object.keys(basePanels)
// for (var i=0; i < panelsArray.length; i++) {
//   var panel = panelsArray[i]
//   for (var j=0; j < panel.features.length; j++) {
//     var feature = panel.features[j]
//     features[feature.expressionExpected] = feature
//   }
// }